add step to check for spanner emulator

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -162,6 +162,21 @@ commands:
           name: cargo spanner build
           command: cargo build --no-default-features --features=syncstorage-db/spanner
       - run:
+          name: Wait for Spanner Emulator
+          command: |-
+            for i in {1..10}; do
+              if nc -z 127.0.0.1 9010; then
+                echo "Spanner emulator running on port 9010."
+                break
+              fi
+              echo "Waiting for Spanner emulator..."
+              sleep 2
+            done
+            if ! nc -z 127.0.0.1 9010; then
+              echo "ERROR: Cannot connect to Spanner emulator at 127.0.0.1:9010. Terminating."
+              exit 1
+            fi
+      - run:
           name: setup spanner
           environment:
             SYNC_SYNCSTORAGE__DATABASE_URL: spanner://projects/test-project/instances/test-instance/databases/test-database
