chore: upload test results to gcs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,6 +5,10 @@
 # DOCKER_PASS
 #
 version: 2.1
+
+orbs:
+  gcp-cli: circleci/gcp-cli@3.3.1
+
 commands:
   display-versions:
     steps:
@@ -163,6 +167,31 @@ commands:
           environment:
               SYNCSTORAGE_RS_IMAGE: app:build
 
+  upload-to-gcs:
+    parameters:
+      source:
+        type: string
+      destination:
+        type: string
+      extension:
+        type: enum
+        enum: ["xml", "json"]
+    steps:
+      - run:
+          name: Upload << parameters.source >> << parameters.extension >> Files to GCS
+          when: always  # Ensure the step runs even if previous steps, like test runs, fail
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+              FILES=$(ls -1 << parameters.source>>/*.<< parameters.extension>> )
+              if [ -z "$FILES" ]; then
+                echo "No << parameters.extension >> files found in << parameters.source >>/"
+                exit 1
+              fi
+              gsutil cp $FILES << parameters.destination >>
+            else
+              echo "Skipping artifact upload, not on 'master' branch."
+            fi
+
   setup-sccache:
     steps:
       - run:
@@ -227,6 +256,7 @@ jobs:
             MYSQL_DATABASE: syncstorage
     resource_class: large
     steps:
+      - gcp-cli/setup
       - checkout
       - display-versions
       - setup-python
@@ -245,6 +275,14 @@ jobs:
       # then run-tokenserver-scripts-tests will fail. These tests expect the db to be
       # configured already, and it appears unit-tests modify the db to the expected state
       - run-tokenserver-scripts-tests
+      - upload-to-gcs:
+          source: workflow/test-results
+          destination: gs://ecosystem-test-eng-metrics/syncstorage-rs/junit
+          extension: xml
+      - upload-to-gcs:
+          source: workflow/test-results
+          destination: gs://ecosystem-test-eng-metrics/syncstorage-rs/coverage
+          extension: json
       #- save-sccache-cache
   build-mysql-image:
     docker:
